### ISSUE TITLE
Questions about the details of the datasets.

### ISSUE THREAD

**Issue by Ricardo-Vv** [dmhyun/PERIS#1]
Could you please provide the script files for processing the yelp and google datasets? Thank you very much.

**Comment by dmhyun** [comment]
I've uploaded the preprocessing codes for Yelp and Google datasets. Please refer to the updated instructions for the preprocessing. 

Thanks for your interest in our work.

**Comment by Ricardo-Vv** [comment]
Thanks for your reply! Best wishes!
